// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjMRUdRsYnRKys0azyYs1xPM1WXMTwzFo',
    appId: '1:23262739465:web:177bc4f4d067203dda8cd8',
    messagingSenderId: '23262739465',
    projectId: 'sign-in-6aaa3',
    authDomain: 'sign-in-6aaa3.firebaseapp.com',
    storageBucket: 'sign-in-6aaa3.appspot.com',
    measurementId: 'G-S11RNMFT3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAooFruYjJbwxtmIRXHUJUAX9eIr_CuSMY',
    appId: '1:23262739465:android:59756c097760ca52da8cd8',
    messagingSenderId: '23262739465',
    projectId: 'sign-in-6aaa3',
    storageBucket: 'sign-in-6aaa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy-tdMBqFIZQb24V7BkwiFALsekDXNqaM',
    appId: '1:23262739465:ios:ab9321349e180ef0da8cd8',
    messagingSenderId: '23262739465',
    projectId: 'sign-in-6aaa3',
    storageBucket: 'sign-in-6aaa3.appspot.com',
    iosClientId: '23262739465-fav55h79uqitip0sro9ck70ah88muvb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy-tdMBqFIZQb24V7BkwiFALsekDXNqaM',
    appId: '1:23262739465:ios:a37395072c40b403da8cd8',
    messagingSenderId: '23262739465',
    projectId: 'sign-in-6aaa3',
    storageBucket: 'sign-in-6aaa3.appspot.com',
    iosClientId: '23262739465-p5ptra7u836nrmi50b7v8bjk2ulfppob.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth.RunnerTests',
  );
}
